# Description (20 points)

Please write a program that prompts the user to enter six integers. <br>
1. The first is the seed for the random number generation. 
2. The second is the lower bound for the random number. 
3. The third is the upper bound for the random number. 
4. The fourth is how many rows of integers you will generate.
5. The fifth is how many numbers you are to generate for each row, and 
6. The sixth is an indicator for sorting. If the value is 0, the numbers are sorted in accending order, if it is 1, the they should be sorted in descending order.

$lower \le \text{random number} < upper$



# Input

random number seed</br>
lower bound</br>
upper bound</br>
rows</br>
amount of number to generate for each row </br>
sorting indicator

# Output

A matrix of random numbers generated and each row are sorted.<br>
Statistic for each row: 1. mean, 2. max, 3. min

# Sample Input 1

 5 <br>
 30 <br>
 500 <br>
 3 <br>
 5 <br>
 1

# Sample Output 1

Matrix: <br>
[[430 385 236 219 148]<br>
 [476 261 258 103  38]<br>
 [441 238 188 142  37]]<br>
Mean: [283.6 227.2 209.2]<br>
Max: [430 476 441]<br>
Min: [148  38  37]

# Reading Input Records (given)
The following lines of code will read in the input integers
Please do not delete np.set_printoptions(legacy="1.13") !!

In [1]:
import numpy as np
np.set_printoptions(legacy="1.13")

In [2]:
# seed = int(input())
# lower = int(input())
# upper = int(input())
# rows = int(input())
# amount = int(input())
# sor = int(input())

In [3]:
seed = 5
lower = 30
upper = 500
rows = 3
amount = 5
sor = 1

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

## Generate the matrix of random numbers 

## Sort each row of the matrix

## Calculate Statistics